apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiagent-service
  namespace: dev
  labels:
    app: aiagent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiagent-service
  template:
    metadata:
      labels:
        app: aiagent-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: 192.168.0.251 # 绑定到这个节点，因为需要弹性公网ip
      containers:
        - name: aiagent-service
          image: swr.la-north-2.myhuaweicloud.com/nextmate/aiagent-service:dev-${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          resources:
            limits:
              cpu: '200m'
              memory: '512Mi'
            requests:
              cpu: '200m'
              memory: '256Mi'
      volumes:
        - name: aiagent-service-volume
          configMap:
            name: aiagent-service
      imagePullSecrets:
        - name: default-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aiagent-service
  namespace: dev